# Generated by Django 4.1.7 on 2023-04-02 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myQuize', '0004_rename_content_myquize_answer_1_remove_myquize_cat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myquize',
            old_name='answer_1',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='myquize',
            name='answer_2',
        ),
        migrations.RemoveField(
            model_name='myquize',
            name='answer_3',
        ),
        migrations.RemoveField(
            model_name='myquize',
            name='answer_correct',
        ),
        migrations.RemoveField(
            model_name='myquize',
            name='question',
        ),
        migrations.AddField(
            model_name='myquize',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myQuize.category'),
        ),
        migrations.CreateModel(
            name='NotMyquize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('question', models.TextField(blank=True)),
                ('answer_1', models.TextField(blank=True)),
                ('answer_2', models.TextField(blank=True)),
                ('answer_3', models.TextField(blank=True)),
                ('answer_correct', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
